// =============== BEGIN inftrees_h ================
#[repr(C)]
#[derive(Copy, Clone)]
pub struct code {
    pub op: u8,
    pub bits: u8,
    pub val: u16,
}

pub type codetype = u32;

pub const DISTS: crate::src::zlib::inftrees::codetype = 2;

pub const LENS: crate::src::zlib::inftrees::codetype = 1;

pub const CODES: crate::src::zlib::inftrees::codetype = 0;

#[no_mangle]

pub static mut inflate_copyright: [i8; 47] = [
    32, 105, 110, 102, 108, 97, 116, 101, 32, 49, 46, 50, 46, 51, 32, 67, 111, 112, 121, 114, 105,
    103, 104, 116, 32, 49, 57, 57, 53, 45, 50, 48, 48, 53, 32, 77, 97, 114, 107, 32, 65, 100, 108,
    101, 114, 32, 0,
];
/*
 If you use the zlib library in a product, an acknowledgment is welcome
 in the documentation of your product. If for some reason you cannot
 include such an acknowledgment, I would appreciate that you keep this
 copyright string in the executable of your product.
*/
/*
  Build a set of tables to decode the provided canonical Huffman code.
  The code lengths are lens[0..codes-1].  The result starts at *table,
  whose indices are 0..2^bits-1.  work is a writable array of at least
  lens shorts, which is used as a work area.  type is the type of code
  to be generated, CODES, LENS, or DISTS.  On return, zero is success,
  -1 is an invalid code, and +1 means that ENOUGH isn't enough.  table
  on return points to the next available entry's address.  bits is the
  requested root table index bits, and on return it is the actual root
  table index bits.  It will differ if the request is greater than the
  longest code or if it is less than the shortest code.
*/
#[no_mangle]

pub unsafe extern "C" fn inflate_table(
    mut type_0: crate::src::zlib::inftrees::codetype,
    mut lens: *mut u16,
    mut codes: u32,
    mut table: *mut *mut crate::src::zlib::inftrees::code,
    mut bits: *mut u32,
    mut work: *mut u16,
) -> i32 {
    let mut len: u32 = 0; /* a code's length in bits */
    let mut sym: u32 = 0; /* index of code symbols */
    let mut min: u32 = 0; /* minimum and maximum code lengths */
    let mut max: u32 = 0; /* number of index bits for root table */
    let mut root: u32 = 0; /* number of index bits for current table */
    let mut curr: u32 = 0; /* code bits to drop for sub-table */
    let mut drop_0: u32 = 0; /* number of prefix codes available */
    let mut left: i32 = 0; /* code entries in table used */
    let mut used: u32 = 0; /* Huffman code */
    let mut huff: u32 = 0; /* for incrementing code, index */
    let mut incr: u32 = 0; /* index for replicating entries */
    let mut fill: u32 = 0; /* low bits for current root entry */
    let mut low: u32 = 0; /* mask for low root bits */
    let mut mask: u32 = 0; /* table entry for duplication */
    let mut this: crate::src::zlib::inftrees::code = crate::src::zlib::inftrees::code {
        op: 0,
        bits: 0,
        val: 0,
    }; /* next available space in table */
    let mut next: *mut crate::src::zlib::inftrees::code =
        0 as *mut crate::src::zlib::inftrees::code; /* base value table to use */
    let mut base: *const u16 = 0 as *const u16; /* extra bits table to use */
    let mut extra: *const u16 = 0 as *const u16; /* use base and extra for symbol > end */
    let mut end: i32 = 0; /* number of codes of each length */
    let mut count: [u16; 16] = [0; 16]; /* offsets in table for each length */
    let mut offs: [u16; 16] = [0; 16];
    static mut lbase: [u16; 31] = [
        3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115,
        131, 163, 195, 227, 258, 0, 0,
    ];
    static mut lext: [u16; 31] = [
        16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20,
        20, 21, 21, 21, 21, 16, 201, 196,
    ];
    static mut dbase: [u16; 32] = [
        1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537,
        2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577, 0, 0,
    ];
    static mut dext: [u16; 32] = [
        16, 16, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26,
        26, 27, 27, 28, 28, 29, 29, 64, 64,
    ];
    /*
      Process a set of code lengths to create a canonical Huffman code.  The
      code lengths are lens[0..codes-1].  Each length corresponds to the
      symbols 0..codes-1.  The Huffman code is generated by first sorting the
      symbols by length from short to long, and retaining the symbol order
      for codes with equal lengths.  Then the code starts with all zero bits
      for the first code of the shortest length, and the codes are integer
      increments for the same length, and zeros are appended as the length
      increases.  For the deflate format, these bits are stored backwards
      from their more natural integer increment ordering, and so when the
      decoding tables are built in the large loop below, the integer codes
      are incremented backwards.

      This routine assumes, but does not check, that all of the entries in
      lens[] are in the range 0..MAXBITS.  The caller must assure this.
      1..MAXBITS is interpreted as that code length.  zero means that that
      symbol does not occur in this code.

      The codes are sorted by computing a count of codes for each length,
      creating from that a table of starting indices for each length in the
      sorted table, and then entering the symbols in order in the sorted
      table.  The sorted table is work[], with that space being provided by
      the caller.

      The length counts are used for other purposes as well, i.e. finding
      the minimum and maximum length codes, determining if there are any
      codes at all, checking for a valid set of lengths, and looking ahead
      at length counts to determine sub-table sizes when building the
      decoding tables.
    */
    /* accumulate lengths for codes (assumes lens[] all in 0..MAXBITS) */
    len = 0;
    while len <= 15 {
        count[len as usize] = 0;
        len = len.wrapping_add(1)
    }
    sym = 0;
    while sym < codes {
        count[*lens.offset(sym as isize) as usize] =
            count[*lens.offset(sym as isize) as usize].wrapping_add(1);
        sym = sym.wrapping_add(1)
    }
    /* bound code lengths, force root to be within code lengths */
    root = *bits;
    max = 15;
    while max >= 1 {
        if count[max as usize] as i32 != 0 {
            break;
        }
        max = max.wrapping_sub(1)
    }
    if root > max {
        root = max
    }
    if max == 0 {
        /* no symbols to code at all */
        this.op = 64;
        this.bits = 1;
        this.val = 0; /* invalid code marker */
        /* no symbols, but wait for decoding to report error */
        let fresh0 = *table; /* make a table to force an error */
        *table = (*table).offset(1);
        *fresh0 = this;
        let fresh1 = *table;
        *table = (*table).offset(1);
        *fresh1 = this;
        *bits = 1u32;
        return 0i32;
    }
    min = 1;
    while min <= 15 {
        if count[min as usize] as i32 != 0 {
            break;
        }
        min = min.wrapping_add(1)
    }
    if root < min {
        root = min
    }
    /* check for an over-subscribed or incomplete set of lengths */
    left = 1;
    len = 1;
    while len <= 15 {
        left <<= 1;
        left -= count[len as usize] as i32;
        if left < 0 {
            return -(1i32);
        }
        len = len.wrapping_add(1)
        /* over-subscribed */
    } /* incomplete set */
    if left > 0 && (type_0 == crate::src::zlib::inftrees::CODES || max != 1) {
        return -(1i32);
    }
    /* generate offsets into symbol table for each length for sorting */
    offs[1] = 0;
    len = 1;
    while len < 15 {
        offs[len.wrapping_add(1u32) as usize] =
            (offs[len as usize] as i32 + count[len as usize] as i32) as u16;
        len = len.wrapping_add(1)
    }
    /* sort symbols by length, by symbol order within each length */
    sym = 0;
    while sym < codes {
        if *lens.offset(sym as isize) as i32 != 0 {
            let fresh2 = offs[*lens.offset(sym as isize) as usize];
            offs[*lens.offset(sym as isize) as usize] =
                offs[*lens.offset(sym as isize) as usize].wrapping_add(1);
            *work.offset(fresh2 as isize) = sym as u16
        }
        sym = sym.wrapping_add(1)
    }
    /*
      Create and fill in decoding tables.  In this loop, the table being
      filled is at next and has curr index bits.  The code being used is huff
      with length len.  That code is converted to an index by dropping drop
      bits off of the bottom.  For codes where len is less than drop + curr,
      those top drop + curr - len bits are incremented through all values to
      fill the table with replicated entries.

      root is the number of index bits for the root table.  When len exceeds
      root, sub-tables are created pointed to by the root entry with an index
      of the low root bits of huff.  This is saved in low to check for when a
      new sub-table should be started.  drop is zero when the root table is
      being filled, and drop is root when sub-tables are being filled.

      When a new sub-table is needed, it is necessary to look ahead in the
      code lengths to determine what size sub-table is needed.  The length
      counts are used for this, and so count[] is decremented as codes are
      entered in the tables.

      used keeps track of how many table entries have been allocated from the
      provided *table space.  It is checked when a LENS table is being made
      against the space in *table, ENOUGH, minus the maximum space needed by
      the worst case distance code, MAXD.  This should never happen, but the
      sufficiency of ENOUGH has not been proven exhaustively, hence the check.
      This assumes that when type == LENS, bits == 9.

      sym increments through all symbols, and the loop terminates when
      all codes of length max, i.e. all codes, have been processed.  This
      routine permits incomplete codes, so another loop after this one fills
      in the rest of the decoding tables with invalid code markers.
    */
    /* set up for code type */
    match type_0 {
        0 => {
            extra = work; /* dummy value--not used */
            base = extra;
            end = 19
        }
        1 => {
            base = lbase.as_ptr();
            base = base.offset(-(257));
            extra = lext.as_ptr();
            extra = extra.offset(-(257));
            end = 256
        }
        _ => {
            /* DISTS */
            base = dbase.as_ptr();
            extra = dext.as_ptr();
            end = -(1)
        }
    }
    /* initialize state for loop */
    huff = 0; /* starting code */
    sym = 0; /* starting code symbol */
    len = min; /* starting code length */
    next = *table; /* current table to fill in */
    curr = root; /* current table index bits */
    drop_0 = 0; /* current bits to drop from code for index */
    low = -(1i32) as u32; /* trigger new sub-table when len > root */
    used = (1) << root; /* use root table entries */
    mask = used.wrapping_sub(1u32); /* mask for comparing low */
    /* check available table space */
    if type_0 == crate::src::zlib::inftrees::LENS && used >= (2048i32 - 592) as u32 {
        return 1i32;
    }
    loop
    /* process all codes and make table entries */
    /* create table entry */
    {
        this.bits = len.wrapping_sub(drop_0) as u8; /* end of block */
        if (*work.offset(sym as isize) as i32) < end {
            this.op = 0;
            this.val = *work.offset(sym as isize)
        } else if *work.offset(sym as isize) as i32 > end {
            this.op = *extra.offset(*work.offset(sym as isize) as isize) as u8;
            this.val = *base.offset(*work.offset(sym as isize) as isize)
        } else {
            this.op = (32i32 + 64) as u8;
            this.val = 0
        }
        /* replicate for those indices with low len bits equal to huff */
        incr = (1) << len.wrapping_sub(drop_0); /* save offset to next table */
        fill = (1) << curr;
        min = fill;
        loop {
            fill = fill.wrapping_sub(incr);
            *next.offset((huff >> drop_0).wrapping_add(fill) as isize) = this;
            if !(fill != 0) {
                break;
            }
        }
        /* backwards increment the len-bit code huff */
        incr = (1) << len.wrapping_sub(1u32);
        while huff & incr != 0 {
            incr >>= 1
        }
        if incr != 0 {
            huff &= incr.wrapping_sub(1u32);
            huff = huff.wrapping_add(incr)
        } else {
            huff = 0
        }
        /* go to next symbol, update count, len */
        sym = sym.wrapping_add(1);
        count[len as usize] = count[len as usize].wrapping_sub(1);
        if count[len as usize] as i32 == 0 {
            if len == max {
                break;
            }
            len = *lens.offset(*work.offset(sym as isize) as isize) as u32
        }
        /* create new sub-table if needed */
        if len > root && huff & mask != low {
            /* if first time, transition to sub-tables */
            if drop_0 == 0 {
                drop_0 = root
            }
            /* increment past last table */
            next = next.offset(min as isize); /* here min is 1 << curr */
            /* determine length of next table */
            curr = len.wrapping_sub(drop_0);
            left = (1) << curr;
            while curr.wrapping_add(drop_0) < max {
                left -= count[curr.wrapping_add(drop_0) as usize] as i32;
                if left <= 0 {
                    break;
                }
                curr = curr.wrapping_add(1);
                left <<= 1
            }
            /* check for enough space */
            used = used.wrapping_add((1u32) << curr);
            if type_0 == crate::src::zlib::inftrees::LENS && used >= (2048i32 - 592) as u32 {
                return 1i32;
            }
            /* point entry in root table to sub-table */
            low = huff & mask;
            (*(*table).offset(low as isize)).op = curr as u8;
            (*(*table).offset(low as isize)).bits = root as u8;
            (*(*table).offset(low as isize)).val = next.wrapping_offset_from(*table) as u16
        }
    }
    /*
      Fill in rest of table for incomplete codes.  This loop is similar to the
      loop above in incrementing huff for table indices.  It is assumed that
      len is equal to curr + drop, so there is no loop needed to increment
      through high index bits.  When the current sub-table is filled, the loop
      drops back to the root table to fill in any remaining entries there.
    */
    this.op = 64; /* invalid code marker */
    this.bits = len.wrapping_sub(drop_0) as u8;
    this.val = 0;
    while huff != 0 {
        /* when done with sub-table, drop back to root table */
        if drop_0 != 0 && huff & mask != low {
            drop_0 = 0;
            len = root;
            next = *table;
            this.bits = len as u8
        }
        /* put invalid code marker in table */
        *next.offset((huff >> drop_0) as isize) = this;
        /* backwards increment the len-bit code huff */
        incr = (1) << len.wrapping_sub(1u32);
        while huff & incr != 0 {
            incr >>= 1
        }
        if incr != 0 {
            huff &= incr.wrapping_sub(1u32);
            huff = huff.wrapping_add(incr)
        } else {
            huff = 0
        }
    }
    /* set return parameters */
    *table = (*table).offset(used as isize);
    *bits = root;
    return 0;
}
